name: Train and Deploy Marathi bert Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Train Model
        run: |
          python train_bert_marathi.py

      - name: Save Model Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: marathi-bert-model
          path: output/

  deploy:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Model Artifacts
        uses: actions/download-artifact@v3
        with:
          name: marathi-bert-model
          path: output/

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instances
        run: |
          az acr build --registry ${{ secrets.ACR_NAME }} --image marathi-qa:v1 .
          az container create --resource-group ${{ secrets.AZURE_RG }} --name marathi-qa-api \
            --image ${{ secrets.ACR_NAME }}.azurecr.io/marathi-qa:v1 --cpu 2 --memory 4 \
            --registry-login-server ${{ secrets.ACR_NAME }}.azurecr.io \
            --registry-username ${{ secrets.AZURE_ACR_USERNAME }} --registry-password ${{ secrets.AZURE_ACR_PASSWORD }} \
            --dns-name-label marathi-qa-api --ports 80

      - name: Verify Deployment
        run: |
          az container show --resource-group ${{ secrets.AZURE_RG }} --name marathi-qa-api --query ipAddress.fqdn
